name: dartray
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.12.0-68.0.dev

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  raylib: ^0.3.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
